spring:
  application:
    name: filez

  # Disable Spring Boot's auto Flyway configuration since we're doing it manually
  flyway:
    enabled: false

  # R2DBC configuration (for application runtime)
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/filemanager
    username: filemanager
    password: filemanager
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  webflux:
    multipart:
      max-in-memory-size: 1MB
      max-disk-usage-per-part: 0

server:
  port: 8080
  max-http-header-size: 64KB
  http2:
    enabled: true

logging:
  level:
    io.filemanager: DEBUG
    io.filemanager.filez.config.ManualFlywayMigration: INFO
    io.filemanager.filez.config.MigrationFileVerifier: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  s3:
    endpoint: http://localhost:9090
    region: us-east-1
    bucket: filemanager-bucket
    access-key: accessKey
    secret-key: secretKey
    path-style-access: true

  av-scan:
    endpoint: http://localhost:8081/scan
    timeout: 300s

  callback:
    base-url: http://localhost:8080

  upload:
    max-file-size: 5GB
    allowed-types: "*"
    temp-cleanup-interval: 300s